chore: add validators
dwarvesf/bookstore-api pull request #14
Opened 2023-09-28 03:50 UTC by datphamcode295

#### What's this PR do?

- [x] Update password validator
- [x] Update author validator

2023-09-28 08:14 UTC, hieuphq requested changes

2023-09-28 08:14 UTC, hieuphq commented on cmd/server/router.go
> +		v.RegisterValidation("authorvalidator", view.AuthorValidator)
```suggestion
		v.RegisterValidation("password", view.PasswordValidator)
		v.RegisterValidation("author", view.AuthorValidator)
```

2023-09-28 08:14 UTC, hieuphq commented on pkg/handler/v1/view/book.go
> +		return true
using regex

2023-09-28 08:14 UTC, hieuphq commented on pkg/handler/v1/view/auth.go
> +		}
using regex

2023-09-29 03:29 UTC, hieuphq requested changes

2023-09-29 03:29 UTC, hieuphq commented on pkg/validator/author.go
> +}
missing the unit test

2023-09-29 03:46 UTC, datphamcode295 commented on pkg/validator/author.go
> +}
updated

2023-10-02 04:42 UTC, hieuphq approved these changes

2023-10-02 04:43 UTC, merged